### ISSUE TITLE
Likely Cruft files in source tree

### ISSUE THREAD

**Issue by kentfredric** [silverdirk/perl-Log-Any-Adapter-TAP#1]
For some reason, there are tar.gz's inside the release tar.gz, with no obvious application: 

https://api.metacpan.org/source/NERDVANA/Log-Any-Adapter-TAP-0.003001/

There's possibly some utility for this, but most cases like this are accidental oversight, especially seeing there's no references in the dist itself to those files.

**Comment by silverdirk** [comment]
Accidental indeed.  I was thinking dist::zilla would omit those, but it appears not.

**Comment by kentfredric** [comment]
Dist::Zilla only does what its told to do. So its likely a plugin configuration you need to square up.

Many of us use `Git::GatherDir` in conjunction with sticking the appropriate declarations in `.gitignore`.

That way, nothing gets added to the dist from the source unless we `git add` it, and then extraneous files we know we never want to add don't risk getting added =)
